fail the script if npm test fails

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -16,6 +16,9 @@ do
     ${i:10}
 
   cd ${i:10}
-  npm test
+  npm test || {
+    echo 'npm test failed'
+    exit 1
+  }
   cd ..
 done
