Rewrite application in TypeScript

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,32 +1,46 @@
 #!/bin/bash
 
+# Detects common CI environments and warn against running in cloud environments.
+if [ -n "$CI" ] || [ -n "$SYSTEM_JOBNAME" ] || [ -n "$GITHUB_ACTIONS" ] || [ -n "${TRAVIS-}" ]; then
+  echo "Do not run this script in a cloud or CI environment."
+  echo "This script - or the create-probot-app.js program - may get stuck at Inquirer prompts and run forever."
+  exit 1
+fi
+
+# Exit immediately if a command returns a non-zero status
 set -e
+
+# Exit when references variables are undefined
+set -u
+
+# Print the executed command
+set -x
 
 # Ensure we're always running from the project root
 cd "$(dirname "$0")/.."
 
 PROJECT_DIR=$(pwd)
 TEMP_DIR="$PROJECT_DIR"/tmp
-mkdir -p $TEMP_DIR
+mkdir -p "$TEMP_DIR"
 
-for i in $PROJECT_DIR/templates/*
+for i in "$PROJECT_DIR"/templates/*
 do
-  template=$(basename $i)
-  echo $template
-  cd $TEMP_DIR
-  rm -rf $template
+  template=$(basename "$i")
+  echo "$template"
+  cd "$TEMP_DIR"
+  rm -rf "$template"
 
-  $PROJECT_DIR/bin/create-probot-app.js \
+  "$PROJECT_DIR"/bin/create-probot-app.js \
     --appName "travis-template-test" \
     --desc "A Probot App for building on Travis" \
     --author "Pro Bawt" \
     --email "probot@example.com" \
     --homepage "https://probot.github.io" \
     --user "probot" \
-    --template $template \
+    --template "$template" \
     --repo "probot/create-probot-app-$template" \
-    $template
+    "$template"
 
-  cd $template
+  cd "$template"
   npm test
 done
